apiVersion: v1
kind: kustomization
metadata:
  name: testnamespace-flux-kustomization
spec:
  path: ./overlays/prod/aws/east/account_name
  sourceRef:
     kind: GitRepository
     name: Flask-App870-sync
----------------

apiVersion: v2
kind: GitRepository
metadata:
  name: Flask-App870
spec:
  url: "ssh://git@github.com:vinayreddy05/Flask-App870.git"


